In [6]:
from PIL import Image
import numpy

In [16]:
channels = 4

image = Image.open('img/22.png', 'r')
width, height = image.size

print('Image data',image.mode, width, height)

pixel_values = list(image.getdata())

print('Image pixel',pixel_values[0])

if image.mode == 'RGB':
    channels = 3
elif image.mode == 'L':
    channels = 1
elif image.mode == 'RGBA ':
    channels = 4
pixel_values = numpy.array(pixel_values).reshape((width, height, channels))

print(pixel_values)

Image data RGBA 25 15
Image pixel (63, 56, 46, 255)
[[[ 63  56  46 255]
  [ 64  57  46 255]
  [ 66  59  48 255]
  ...
  [ 60  53  44 255]
  [ 59  51  42 255]
  [ 58  50  42 255]]

 [[ 57  50  41 255]
  [ 56  49  41 255]
  [ 56  49  40 255]
  ...
  [ 69  62  51 255]
  [ 69  62  51 255]
  [ 68  61  50 255]]

 [[ 68  61  50 255]
  [ 67  60  49 255]
  [ 65  58  48 255]
  ...
  [ 54  46  38 255]
  [ 54  46  38 255]
  [ 53  46  38 255]]

 ...

 [[ 49  43  34 255]
  [ 48  43  34 255]
  [ 48  42  34 255]
  ...
  [ 43  38  30 255]
  [ 44  39  30 255]
  [ 45  39  31 255]]

 [[ 45  39  31 255]
  [ 44  38  30 255]
  [ 44  37  30 255]
  ...
  [ 47  56  24 255]
  [ 78  89  37 255]
  [ 75  81  32 255]]

 [[ 73  79  32 255]
  [ 54  59  20 255]
  [ 64  69  21 255]
  ...
  [ 59  65  22 255]
  [ 61  65  22 255]
  [ 76  81  29 255]]]
